sudo: false
language: node_js

matrix:
  include:
  - os: linux
    before_install:
    - sudo apt-get update
    - sudo apt-get install -y fakeroot
  - os: osx
    osx_image: xcode9.4

node_js:
- 'node'

install:
- npm install

script:
- npm run make
